### ISSUE TITLE
Drop BA metrics into a JSON file (with pose errors)

### ISSUE THREAD

**Issue by ayushbaid** [borglab/gtsfm#137]
Currently few metrics from BA are just logged and not dumped. 

Example: 
[2021-04-07 01:19:01,343 INFO bundle_adjustment.py line 165 569967] initial error: 64453.72
[2021-04-07 01:19:01,344 INFO bundle_adjustment.py line 166 569967] final error: 1372.83

**Comment by akshay-krishnan** [comment]
I believe this has been fixed?

**Comment by johnwlambert** [comment]
While we dump the unfiltered and filtered reprojection errors, we are still not dumping the final pose errors, which I think is the most important. So we should do that.

**Comment by ayushbaid** [comment]
Should be easy to write and we can let one of the new folks to pick this up.

**Comment by johnwlambert** [comment]
Will be fixed. by https://github.com/borglab/gtsfm/pull/252
